/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package open.book.search;

import java.io.IOException;

import org.json.simple.JSONObject;
import org.json.simple.parser.ParseException;

import Requests.Get;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Get get = new Get("https://www.loc.gov/search/?q=baseball&fo=json&at=results");
        try {
            get.run();
            JSONObject response = get.parseResponse();
            System.out.println(response);
        } catch (IOException e) {
            System.out.println("Could not print response");
            e.printStackTrace();
        } catch (ParseException e) {
            System.out.println("Could not parse output");
            e.printStackTrace();
        }
    }
}
